console:
  image: peerbelt/pb-core-console
  ports:
    - "44444:80"
  restart: always

consoleapi:
  image: peerbelt/pb-core-console-api
  ports:
    - "33333:3000"
  links:
    - trackingapi:trackingapi
  volumes:
    - /var/log/console-api:/var/log/console-api/
    - /var/data/console-api:/home/pb-core-console-api/data
  environment:
    - NODE_ENV=prod
    - NEW_RELIC_APP_NAME=plus-iad-consoleapi
    - NEW_RELIC_LICENSE_KEY=NEWRELIC_LICENSE
    - TRACKINGAPI_ACCESS_TOKEN=TRAPI_ACCESS_TOKEN
  restart: always

saas:
  image: peerbelt/pb-core-saas-website
  ports:
    - "44445:80"
  restart: always

trackingapi:
  image: peerbelt/pb-core-tracking-api
  mem_limit: 2000m
  log_driver: "none"
  ports:
    - "22222:3001"
  volumes:
    - /var/log/tracking-api:/var/log/tracking-api/
  environment:
    - NEW_RELIC_APP_NAME=plus-iad-trackingapi
    - NEW_RELIC_LICENSE_KEY=NEWRELIC_LICENSE
    - CASSANDRA_HOST=10.115.81.69
    - ELASTICSEARCH_HOST=10.115.81.118
    - OPSCENTER_HOST=10.148.13.50
    - WORKER_TTL_MINUTES=120
  restart: always

consumerapi:
  image: peerbelt/pb-core-consumer-api
  log_driver: "none"
  ports:
    - "11111:3000"
  volumes:
    - /var/log/consumer:/var/log/consumer/
  environment:
    - NEW_RELIC_APP_NAME=plus-iad-consumerapi
    - NEW_RELIC_LICENSE_KEY=NEWRELIC_LICENSE
    - CASSANDRA_HOST=10.115.81.69
    - ELASTICSEARCH_HOST=10.115.81.118
    - VERBOSE=1
  restart: always
