cassandra:
  image: peerbelt/cassandra

elasticsearch:
  image: peerbelt/elastic-dummy
  ports:
    - "9200:9200"

console:
  image: peerbelt/pb-core-console
  ports:
    - "44444:80"
 
consoleapi:
  image: peerbelt/pb-core-console-api
  ports:
    - "33333:3000"
  volumes:
    - /var/log/console-api:/var/log/console-api/
    - /var/data/console-api:/home/pb-core-console-api/data

saas:
  image: peerbelt/pb-core-saas-website
  ports:
    - "44445:80"

trackingapi:
  image: peerbelt/pb-core-tracking-api
  ports:
    - "22222:3001"
  links:
    - cassandra:cassandra
  volumes:
    - /var/log/tracking-api:/var/log/tracking-api/
    - /var/data/tracking-api:/home/pb-core-tracking-api/data

consumerapi:
  image: peerbelt/pb-core-consumer-api
  ports:
    - "11111:3000"
  links:
    - elasticsearch:elasticsearch
  volumes:
    - /var/log/consumer:/var/log/consumer/
    - /var/data/consumer-api:/home/pb-core-consumer-api/data  
digest:
  image: peerbelt/pb-core-digest
  links:
    - elasticsearch:elasticsearch
    - cassandra:cassandra
  volumes:
    - /var/log/digest:/var/log/digest/
    - /var/data/digest:/home/pb-core-digest-api/data



