console:
  image: peerbelt/pb-core-console
  ports:
    - "44444:80"
  restart: always
  
consoleapi:
  image: peerbelt/pb-core-console-api
  ports:
    - "33333:3000"
  links:
    - trackingapi:trackingapi
  volumes:
    - /var/log/console-api:/var/log/console-api/
    - /var/data/console-api:/home/pb-core-console-api/data
  environment:
    - NODE_ENV=cd
    - NEW_RELIC_APP_NAME=plus-iad-consoleapi
    - NEW_RELIC_LICENSE_KEY=e05c8ac325c1bab960e211f52223216abab870d7   
  restart: always
  
saas:
  image: peerbelt/pb-core-saas-website
  ports:
    - "44445:80"
  restart: always

trackingapi:
  image: peerbelt/pb-core-tracking-api
  ports:
    - "22222:3001"
  volumes:
    - /var/log/tracking-api:/var/log/tracking-api/
  environment:
    - NEW_RELIC_APP_NAME=plus-iad-trackingapi
    - NEW_RELIC_LICENSE_KEY=e05c8ac325c1bab960e211f52223216abab870d7
    - CASSANDRA_HOST='"10.209.3.172","10.209.3.100","10.209.97.182"'
  restart: always

