console:
  image: peerbelt/pb-core-console
  ports:
    - "44444:80"

consoleapi:
  image: peerbelt/pb-core-console-api
  ports:
    - "33333:3000"
  environment:
    - NODE_ENV=prod
    - TRACKINGAPI_URL=https://cd-eu-tracking.peerbelt.com/api/v1
  volumes:
    - /var/log/console-api:/var/log/console-api/

saas:
  image: peerbelt/pb-core-saas-website
  ports:
    - "44445:80"



