cassandra:
  image: peerbelt/cassandra
  restart: always

elasticsearch:
  image: peerbelt/elastic-dummy
  ports:
    - "9200:9200"
  restart: always

console:
  image: peerbelt/pb-core-console
  ports:
    - "44444:80"
  restart: always
  
consoleapi:
  image: peerbelt/pb-core-console-api
  ports:
    - "33333:3000"
  links:
    - trackingapi:trackingapi
  volumes:
    - /var/log/console-api:/var/log/console-api/
    - /var/data/console-api:/home/pb-core-console-api/data
  environment:
    - NODE_ENV=cd
    - NEW_RELIC_APP_NAME=cd-iad-consoleapi
    - NEW_RELIC_LICENSE_KEY=6b69530bc9d305b58a250460b0defbdb82423859    
  restart: always
  
saas:
  image: peerbelt/pb-core-saas-website
  ports:
    - "44445:80"
  restart: always

trackingapi:
  image: peerbelt/pb-core-tracking-api
  ports:
    - "22222:3001"
  links:
    - cassandra:cassandra
  volumes:
    - /var/log/tracking-api:/var/log/tracking-api/
  environment:
    - NEW_RELIC_APP_NAME=cd-iad-trackingapi
    - NEW_RELIC_LICENSE_KEY=6b69530bc9d305b58a250460b0defbdb82423859
  restart: always

consumerapi:
  image: peerbelt/pb-core-consumer-api
  ports:
    - "11111:3000"
  links:
    - elasticsearch:elasticsearch
  volumes:
    - /var/log/consumer:/var/log/consumer/
  environment:
    - NEW_RELIC_APP_NAME=cd-iad-consumerapi
    - NEW_RELIC_LICENSE_KEY=6b69530bc9d305b58a250460b0defbdb82423859
  restart: always
  
  digest:
  image: peerbelt/pb-core-digest
  links:
    - elasticsearch:elasticsearch
    - cassandra:cassandra
  volumes:
    - /var/log/digest:/var/log/digest/
  environment:
    - NEW_RELIC_APP_NAME=cd-iad-digest
    - NEW_RELIC_LICENSE_KEY=6b69530bc9d305b58a250460b0defbdb82423859
  restart: always
